'use client';

import { FormEvent,useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import FigmaFrame from './FigmaFrame';
import { frames } from '@/lib/figmaFrames';
import { FigmaModal,InlineStatus } from './FigmaModal';

type Me={name:string;email:string;profile:Record<string,string|null>;settings:Record<string,boolean|string>|null};

export default function FigmaSettingsPageClient(){
  const router=useRouter();const[me,setMe]=useState<Me|null>(null);const[settings,setSettings]=useState<Record<string,boolean|string>>({});const[edit,setEdit]=useState(false);const[passwordOpen,setPasswordOpen]=useState(false);const[deleteOpen,setDeleteOpen]=useState(false);const[form,setForm]=useState<Record<string,string>>({});const[passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirm:''});const[deleteForm,setDeleteForm]=useState({password:'',confirmation:''});const[status,setStatus]=useState<{error?:string;success?:string;loading?:boolean}>({});
  async function load(){const response=await fetch('/api/auth/me');const payload=await response.json();if(!response.ok)throw new Error(payload.error);setMe(payload);setSettings(payload.settings||{});setForm({name:payload.name||'',birthDate:payload.profile?.birthDate||'',gender:payload.profile?.gender||'female',phone:payload.profile?.phone||'',city:payload.profile?.city||''});}
  useEffect(()=>{load().catch((error)=>setStatus({error:error.message}));},[]);
  async function updateSettings(patch:Record<string,boolean|string>){const next={...settings,...patch};setSettings(next);setStatus({loading:true});try{const response=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setStatus({success:'Đã lưu cài đặt'});}catch(error){setStatus({error:error instanceof Error?error.message:'Không thể lưu cài đặt'});}}
  async function saveProfile(event:FormEvent){event.preventDefault();setStatus({loading:true});try{const response=await fetch('/api/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);await load();setEdit(false);setStatus({success:'Đã cập nhật thông tin tài khoản'});}catch(error){setStatus({error:error instanceof Error?error.message:'Không thể cập nhật'});}}
  async function changePassword(event:FormEvent){event.preventDefault();if(passwords.newPassword!==passwords.confirm)return setStatus({error:'Mật khẩu xác nhận không khớp'});setStatus({loading:true});try{const response=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(passwords)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setPasswordOpen(false);setPasswords({currentPassword:'',newPassword:'',confirm:''});setStatus({success:'Đã đổi mật khẩu'});}catch(error){setStatus({error:error instanceof Error?error.message:'Không thể đổi mật khẩu'});}}
  async function deleteAccount(event:FormEvent){event.preventDefault();setStatus({loading:true});try{const response=await fetch('/api/auth/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify(deleteForm)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);router.push('/register');router.refresh();}catch(error){setStatus({error:error instanceof Error?error.message:'Không thể xóa tài khoản'});}}
  const toggle=(key:string)=>updateSettings({[key]:!Boolean(settings[key])});
  const profile=me?.profile||{};
  return <>
    <FigmaFrame frame={frames.settings} desktopNav>
      {me&&<>
        {[{value:me.name,left:415,top:180},{value:me.email,left:415,top:239},{value:String(profile.phone||''),left:415,top:298},{value:String(profile.birthDate||''),left:686,top:180},{value:String(profile.gender||''),left:686,top:239},{value:String(profile.city||''),left:686,top:298}].map((item,index)=><div key={index} className="figma-dynamic-text" style={{left:item.left,top:item.top,width:235,height:23,fontSize:9,padding:'5px'}}>{item.value||'Chưa cập nhật'}</div>)}
      </>}
      <button className="figma-action" style={{left:895,top:114,width:75,height:31}} onClick={()=>setEdit(true)} aria-label="Chỉnh sửa tài khoản"/>
      {['emailNotifications','appNotifications','learningReminders','newsletter'].map((key,index)=><button key={key} type="button" className={`figma-choice ${settings[key]?'selected':''}`} style={{left:935,top:426+index*48,width:35,height:28,borderRadius:20}} onClick={()=>toggle(key)} aria-label={key}/>)}
      <button type="button" className={`figma-choice ${settings.darkMode?'selected':''}`} style={{left:578,top:691,width:38,height:27,borderRadius:20}} onClick={()=>toggle('darkMode')} aria-label="Chế độ tối"/>
      <select className="figma-select-overlay" style={{left:1280,top:413,width:105,height:34,border:0}} value={String(settings.profileVisibility||'private')} onChange={(event)=>updateSettings({profileVisibility:event.target.value})}><option value="private">Chỉ mình tôi</option><option value="friends">Bạn bè</option><option value="public">Mọi người</option></select>
      <select className="figma-select-overlay" style={{left:1280,top:461,width:105,height:34,border:0}} value={String(settings.emailVisibility||'private')} onChange={(event)=>updateSettings({emailVisibility:event.target.value})}><option value="private">Chỉ mình tôi</option><option value="friends">Bạn bè</option><option value="public">Mọi người</option></select>
      <select className="figma-select-overlay" style={{left:1280,top:509,width:105,height:34,border:0}} value={String(settings.phoneVisibility||'friends')} onChange={(event)=>updateSettings({phoneVisibility:event.target.value})}><option value="private">Chỉ mình tôi</option><option value="friends">Bạn bè</option><option value="public">Mọi người</option></select>
      <button className="figma-action" style={{left:1028,top:650,width:357,height:72}} onClick={()=>setPasswordOpen(true)} aria-label="Đổi mật khẩu"/>
      <button className="figma-action" style={{left:768,top:931,width:121,height:37}} onClick={()=>setDeleteOpen(true)} aria-label="Xóa tài khoản"/>
      {status.error&&<div className="figma-overlay-error" style={{left:1020,top:873,width:360}}>{status.error}</div>}
      {status.success&&<div className="figma-overlay-success" style={{left:1020,top:873,width:360}}>{status.success}</div>}
    </FigmaFrame>
    <FigmaModal open={edit} title="Chỉnh sửa thông tin tài khoản" onClose={()=>setEdit(false)}>
      <form onSubmit={saveProfile}><InlineStatus error={status.error}/><div className="ct-form-grid">{['name','birthDate','phone','city'].map((key)=><div className="ct-form-field" key={key}><label>{({name:'Họ và tên',birthDate:'Ngày sinh',phone:'Số điện thoại',city:'Địa chỉ'} as Record<string,string>)[key]}</label><input value={form[key]||''} onChange={(event)=>setForm({...form,[key]:event.target.value})}/></div>)}<div className="ct-form-field"><label>Giới tính</label><select value={form.gender||'female'} onChange={(event)=>setForm({...form,gender:event.target.value})}><option value="female">Nữ</option><option value="male">Nam</option><option value="other">Khác</option></select></div></div><div className="ct-actions"><button className="ct-primary" disabled={status.loading}>Lưu thay đổi</button></div></form>
    </FigmaModal>
    <FigmaModal open={passwordOpen} title="Đổi mật khẩu" onClose={()=>setPasswordOpen(false)}><form onSubmit={changePassword}><InlineStatus error={status.error}/><div className="ct-form-field"><label>Mật khẩu hiện tại</label><input type="password" autoComplete="current-password" value={passwords.currentPassword} onChange={(event)=>setPasswords({...passwords,currentPassword:event.target.value})}/></div><div className="ct-form-field"><label>Mật khẩu mới</label><input type="password" autoComplete="new-password" value={passwords.newPassword} onChange={(event)=>setPasswords({...passwords,newPassword:event.target.value})}/></div><div className="ct-form-field"><label>Xác nhận mật khẩu mới</label><input type="password" autoComplete="new-password" value={passwords.confirm} onChange={(event)=>setPasswords({...passwords,confirm:event.target.value})}/></div><div className="ct-actions"><button className="ct-primary" disabled={status.loading}>Cập nhật mật khẩu</button></div></form></FigmaModal>
    <FigmaModal open={deleteOpen} title="Xóa tài khoản" onClose={()=>setDeleteOpen(false)}><form onSubmit={deleteAccount}><InlineStatus error={status.error}/><p>Thao tác này xóa vĩnh viễn toàn bộ hồ sơ, lịch sử AI, mô phỏng, report và roadmap của bạn.</p><div className="ct-form-field"><label>Mật khẩu</label><input type="password" value={deleteForm.password} onChange={(event)=>setDeleteForm({...deleteForm,password:event.target.value})}/></div><div className="ct-form-field"><label>Nhập chính xác “XOA TAI KHOAN”</label><input value={deleteForm.confirmation} onChange={(event)=>setDeleteForm({...deleteForm,confirmation:event.target.value})}/></div><div className="ct-actions"><button type="button" className="ct-secondary" onClick={()=>setDeleteOpen(false)}>Hủy</button><button className="ct-danger" disabled={status.loading}>Xóa vĩnh viễn</button></div></form></FigmaModal>
  </>;
}
